// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxtFqHVwdLMcVjp0GKf1NS2icIuNUxl4',
    appId: '1:649097137411:web:0a4dc838ff614a69786d36',
    messagingSenderId: '649097137411',
    projectId: 'chat-app-flutter-d3b0d',
    authDomain: 'chat-app-flutter-d3b0d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-d3b0d.firebasestorage.app',
    measurementId: 'G-R8EG9SKPJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzy8U057h0NyPiPIvjadhNltX3iZln8A',
    appId: '1:649097137411:android:4f45a1ae28f1ae65786d36',
    messagingSenderId: '649097137411',
    projectId: 'chat-app-flutter-d3b0d',
    storageBucket: 'chat-app-flutter-d3b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiaAmm24Pfy0UtWuL5OPkSXAeY9yLEYzE',
    appId: '1:649097137411:ios:4f4fcb98a0681063786d36',
    messagingSenderId: '649097137411',
    projectId: 'chat-app-flutter-d3b0d',
    storageBucket: 'chat-app-flutter-d3b0d.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiaAmm24Pfy0UtWuL5OPkSXAeY9yLEYzE',
    appId: '1:649097137411:ios:4f4fcb98a0681063786d36',
    messagingSenderId: '649097137411',
    projectId: 'chat-app-flutter-d3b0d',
    storageBucket: 'chat-app-flutter-d3b0d.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxtFqHVwdLMcVjp0GKf1NS2icIuNUxl4',
    appId: '1:649097137411:web:16cbcf1c97ccec72786d36',
    messagingSenderId: '649097137411',
    projectId: 'chat-app-flutter-d3b0d',
    authDomain: 'chat-app-flutter-d3b0d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-d3b0d.firebasestorage.app',
    measurementId: 'G-L9H75FSEVG',
  );
}
