// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHXJL5UC_TAXxTxeZg0EtQ_UFKT1c118',
    appId: '1:576279911824:web:9a7402b63f96047593e715',
    messagingSenderId: '576279911824',
    projectId: 'foodup-3a217',
    authDomain: 'foodup-3a217.firebaseapp.com',
    storageBucket: 'foodup-3a217.firebasestorage.app',
    measurementId: 'G-VX1V8MVZXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3JbAy9-0_sJoxXn3ubnSSxw-UAGZB_Y',
    appId: '1:576279911824:android:05a00faf2a38cd5393e715',
    messagingSenderId: '576279911824',
    projectId: 'foodup-3a217',
    storageBucket: 'foodup-3a217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqC8ZgtJOWE-QDviiW5F1qstwY-_Z0IFo',
    appId: '1:576279911824:ios:392f40569ed2a1ba93e715',
    messagingSenderId: '576279911824',
    projectId: 'foodup-3a217',
    storageBucket: 'foodup-3a217.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqC8ZgtJOWE-QDviiW5F1qstwY-_Z0IFo',
    appId: '1:576279911824:ios:392f40569ed2a1ba93e715',
    messagingSenderId: '576279911824',
    projectId: 'foodup-3a217',
    storageBucket: 'foodup-3a217.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVHXJL5UC_TAXxTxeZg0EtQ_UFKT1c118',
    appId: '1:576279911824:web:ebb7061ac59f036393e715',
    messagingSenderId: '576279911824',
    projectId: 'foodup-3a217',
    authDomain: 'foodup-3a217.firebaseapp.com',
    storageBucket: 'foodup-3a217.firebasestorage.app',
    measurementId: 'G-WTXYFVVVSV',
  );
}
