name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.11
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  curved_navigation_bar: ^1.0.6
  cached_network_image: ^3.4.1
  animate_do: ^4.2.0
  flutter_animate: ^4.5.2
  auto_animated: ^3.2.0
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
