// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx55wGrqTWwQozYvPfzPENQnoJwT13eu0',
    appId: '1:577714180040:web:ed2507d84f015ecf2abafd',
    messagingSenderId: '577714180040',
    projectId: 'ai-image-generator-28ed3',
    authDomain: 'ai-image-generator-28ed3.firebaseapp.com',
    storageBucket: 'ai-image-generator-28ed3.firebasestorage.app',
    measurementId: 'G-6VCYLV7T6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbpTgoOEKAoFqRwnKfj_8k9LYimE8O7d8',
    appId: '1:577714180040:android:1dcbc720f6e729f52abafd',
    messagingSenderId: '577714180040',
    projectId: 'ai-image-generator-28ed3',
    storageBucket: 'ai-image-generator-28ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2uT_1p_iyuPeQ6bwD5_-cyN7XND-_VM',
    appId: '1:577714180040:ios:e82d8317562922fc2abafd',
    messagingSenderId: '577714180040',
    projectId: 'ai-image-generator-28ed3',
    storageBucket: 'ai-image-generator-28ed3.firebasestorage.app',
    iosBundleId: 'com.example.aiImageProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2uT_1p_iyuPeQ6bwD5_-cyN7XND-_VM',
    appId: '1:577714180040:ios:e82d8317562922fc2abafd',
    messagingSenderId: '577714180040',
    projectId: 'ai-image-generator-28ed3',
    storageBucket: 'ai-image-generator-28ed3.firebasestorage.app',
    iosBundleId: 'com.example.aiImageProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx55wGrqTWwQozYvPfzPENQnoJwT13eu0',
    appId: '1:577714180040:web:83e1c41fc1b7e8ed2abafd',
    messagingSenderId: '577714180040',
    projectId: 'ai-image-generator-28ed3',
    authDomain: 'ai-image-generator-28ed3.firebaseapp.com',
    storageBucket: 'ai-image-generator-28ed3.firebasestorage.app',
    measurementId: 'G-KYJ8K4JTHM',
  );
}
