// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZY3Kq-55EQGxpBgtT_QPOMCpS6lOhUU',
    appId: '1:119234853737:web:2e1647a642ec44310edbf8',
    messagingSenderId: '119234853737',
    projectId: 'ecommerce-app-7fad9',
    authDomain: 'ecommerce-app-7fad9.firebaseapp.com',
    storageBucket: 'ecommerce-app-7fad9.firebasestorage.app',
    measurementId: 'G-WZ2DH620W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPhNYZSGGvy26wGKRsBh9J3j_gXdYZKM',
    appId: '1:119234853737:android:64bdeecb163fbbac0edbf8',
    messagingSenderId: '119234853737',
    projectId: 'ecommerce-app-7fad9',
    storageBucket: 'ecommerce-app-7fad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahRI2XmEEOqWSyx5I_PPLUSnOsj7Ybbk',
    appId: '1:119234853737:ios:ce02aa09f6464d330edbf8',
    messagingSenderId: '119234853737',
    projectId: 'ecommerce-app-7fad9',
    storageBucket: 'ecommerce-app-7fad9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

}