// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGeGNlfb4eu-epExrnAvo-JZnRSsoS5vc',
    appId: '1:449723417788:web:463934a2e457b01b5cbcb9',
    messagingSenderId: '449723417788',
    projectId: 'bookgenerationapp',
    authDomain: 'bookgenerationapp.firebaseapp.com',
    storageBucket: 'bookgenerationapp.firebasestorage.app',
    measurementId: 'G-G9BE0236FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8B3Vxy0U0RZZhIIBgcHDaNDwEe36DEWM',
    appId: '1:449723417788:android:a03b6147442491215cbcb9',
    messagingSenderId: '449723417788',
    projectId: 'bookgenerationapp',
    storageBucket: 'bookgenerationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvPc9n_XPvrJ99lZVZWG5yVKaGwvdUgg',
    appId: '1:449723417788:ios:80741f7fe47d0b805cbcb9',
    messagingSenderId: '449723417788',
    projectId: 'bookgenerationapp',
    storageBucket: 'bookgenerationapp.firebasestorage.app',
    iosBundleId: 'com.example.aiBookSummaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAvPc9n_XPvrJ99lZVZWG5yVKaGwvdUgg',
    appId: '1:449723417788:ios:80741f7fe47d0b805cbcb9',
    messagingSenderId: '449723417788',
    projectId: 'bookgenerationapp',
    storageBucket: 'bookgenerationapp.firebasestorage.app',
    iosBundleId: 'com.example.aiBookSummaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGeGNlfb4eu-epExrnAvo-JZnRSsoS5vc',
    appId: '1:449723417788:web:335c205502dd1b285cbcb9',
    messagingSenderId: '449723417788',
    projectId: 'bookgenerationapp',
    authDomain: 'bookgenerationapp.firebaseapp.com',
    storageBucket: 'bookgenerationapp.firebasestorage.app',
    measurementId: 'G-C2FV4VES4K',
  );
}
